__asm__(".global PMPI_Pcontrol\n"
        ".weak MPI_Pcontrol\n"
        ".set MPI_Pcontrol,PMPI_Pcontrol\n"
        ".extern in_w\n"
        ".extern A_MPI_Pcontrol\n"
        ".extern R_MPI_Pcontrol\n"
        ".type PMPI_Pcontrol,@function\n"
        ".text\n"
        "PMPI_Pcontrol:\n"
#ifdef __aarch64__
        "adrp x8, :gottprel:in_w\n"
        "ldr x8, [x8, :gottprel_lo12:in_w]\n"
        "mrs x9, TPIDR_EL0\n"
        "ldr w8, [x9, x8]\n"
        "cbnz w8, inwrap_MPI_Pcontrol\n"
        "b A_MPI_Pcontrol\n"
        "inwrap_MPI_Pcontrol:\n"
        "b R_MPI_Pcontrol\n"
#else
         "push %rbp\n"
         "mov %rsp, %rbp\n"
         "sub $0x10, %rsp\n"
         "mov %rdi, -0x8(%rbp)\n"
         ".byte 0x66\n"
         "leaq in_w@tlsgd(%rip), %rdi\n"
         ".value 0x6666\n"
         "rex64\n"
         "call __tls_get_addr@PLT\n"
         "mov -0x8(%rbp), %rdi\n"
         "leave\n"
         "cmpl $0x0, 0x0(%rax)\n"
         "jne inwrap_MPI_Pcontrol\n"
         "jmp *A_MPI_Pcontrol@GOTPCREL(%rip)\n"
         "inwrap_MPI_Pcontrol:\n"
         "jmp *R_MPI_Pcontrol@GOTPCREL(%rip)\n"
#endif
        ".size PMPI_Pcontrol,.-PMPI_Pcontrol\n"

);

